### ISSUE TITLE
Iteration 3 - Network Requests & Async JS

### ISSUE THREAD

**Issue by Scotty-Brown** [Scotty-Brown/rancid-tomatillos#2]
## User Story

- When the server returns a 500 error, the user will see proper error handling

**Comment by Scotty-Brown** [comment]
- Revisit code snippet below to determine if this is the best place for the conditional to live or if we need to move it to our app.js file



![Image](https://github.com/Scotty-Brown/rancid-tomatillos/assets/130028791/3cc87dad-1af8-4c43-ad86-71b2f2d84b95)

**Comment by judy0ye** [comment]
## Acceptance Criteria:
*Scenario: The viewer clicks on a movie that doesn't have any data on the server.*

Given that there is a general problem with the website's server
When the viewer clicks on the movie
An error message is shown on the screen

**Comment by judy0ye** [comment]
- revisit commented out code snippet to determine whether to keep catch in apiCalls

![Image](https://github.com/Scotty-Brown/rancid-tomatillos/assets/129805348/7e4cea05-9caa-4857-8896-fc07079feeb7)
